import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Launch a newsletter using Github!
        </h1>

        <p className={styles.description}>
          Issues stored as markdown files in any repository (e.g. your blog).
        </p>

        <div className={styles.grid}>
          <Image src="/images/demo.png" width={2260} height={1156} />
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://twitter.com/git_letter"
          target="_blank"
          rel="noopener noreferrer"
        >
          Twitter
        </a>
      </footer>
    </div>
  )
}

export default Home
