name: chromatic
on: [pull_request]
jobs:
  build:
    name: Publish to Chromatic
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Install modules
      run: yarn
    - name: Publish to Chromatic
      run: yarn chromatic --project-token ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
