name: CI
on: [pull_request]
jobs:
  build:
    name: Lint, compile, unit test, and deploy to Chromatic
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install modules
      run: yarn
    - name: Run ESLint
      run: yarn lint
    - name: Compile TypeScript
      run: yarn tsc
    - name: Run unit tests
      run: yarn test
    - name: Deploy to Chromatic
      run: yarn chromatic --project-token ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
