name: CI
on: [pull_request]
jobs:
  build:
    name: Lint, tsc and tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install modules
      run: yarn install
    - name: Run ESLint
      run: yarn lint
    - name: Compile TypeScript
      run: yarn tsc
    - name: Run tests
      run: yarn test
