name: test
on: [pull_request]
jobs:
  build:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install modules
      run: yarn
    - name: Run unit tests
      run: yarn test
